In [2]:
import numpy as np

In [3]:
# questão 1
random_array = np.random.randint(10, 99, (5,5))
print(random_array)

[[87 35 91 71 84]
 [12 91 27 96 98]
 [86 87 21 70 48]
 [61 53 94 41 90]
 [63 48 38 41 13]]


In [4]:
# questão 2
np.fill_diagonal(random_array, -1)
print(random_array)

[[-1 35 91 71 84]
 [12 -1 27 96 98]
 [86 87 -1 70 48]
 [61 53 94 -1 90]
 [63 48 38 41 -1]]


In [5]:
# questão 3
new_random_array = np.random.randint(1, 1000, 100)
print("Matriz original:")
print(new_random_array)
number = 3
replacement_value = -1

new_random_array[new_random_array % number == 0] = replacement_value
print("\n Nova matriz:")
print(new_random_array)


Matriz original:
[405 671 464 466  86  45 732  82 628 603 944 361 166 758 261 464 509 557
 587 947 458 764 652 680 730 187 578 645 445 363 539  26 972 702 105 127
 497 986 804 566 123 751 299 423 357 930 688 577  59 496 392 110 763  21
 995 907 182 424 429 262 174 889 138 141 674 271 828 591 461 548 947 209
  47 295 911 929 534 280  65 908 752 905 219 356 314   5 666 283 850  90
 960 475 561 230 551 729 915 973 313 794]

 Nova matriz:
[ -1 671 464 466  86  -1  -1  82 628  -1 944 361 166 758  -1 464 509 557
 587 947 458 764 652 680 730 187 578  -1 445  -1 539  26  -1  -1  -1 127
 497 986  -1 566  -1 751 299  -1  -1  -1 688 577  59 496 392 110 763  -1
 995 907 182 424  -1 262  -1 889  -1  -1 674 271  -1  -1 461 548 947 209
  47 295 911 929  -1 280  65 908 752 905  -1 356 314   5  -1 283 850  -1
  -1 475  -1 230 551  -1  -1 973 313 794]


In [6]:
# questão 4
array_one = np.random.randint(1, 50, (3,3))

print("Matriz um:")
print(array_one)

array_two = np.random.randint(1, 50,(3,3))
print("\n Matriz dois:")
print(array_two)

Matriz um:
[[11 20 13]
 [15 21 25]
 [34  5 10]]

 Matriz dois:
[[29 18 34]
 [39  8 15]
 [29 41 24]]


In [7]:
# questão 5
squared_array_one = array_one ** 2
array_two[array_two == 0] = 1

# operação
result = squared_array_one / array_two

print("resultado:")
print(result)

resultado:
[[ 4.17241379 22.22222222  4.97058824]
 [ 5.76923077 55.125      41.66666667]
 [39.86206897  0.6097561   4.16666667]]


In [8]:
# questão 6
while True:
  array_4x4 = np.random.randint(1, 30, (4,4))
  array_inv = np.linalg.inv(array_4x4)
  break
print("Array 4x4 padrão:")
print(array_4x4)
print("\n Matriz inversa:")
print(array_inv)


Array 4x4 padrão:
[[ 5  6 22 27]
 [27 10  4 21]
 [23 12 23 20]
 [27 23  6 10]]

 Matriz inversa:
[[-0.05045028  0.02968204  0.04980702 -0.02573056]
 [ 0.04193941 -0.04008737 -0.05345454  0.07785616]
 [-0.01254718 -0.04025702  0.06605121 -0.01368527]
 [ 0.04728345  0.03621365 -0.05116424 -0.00138549]]


In [9]:
# questão 7
array_10x10 = np.zeros((10,10))
print("Matriz original: ")
print(array_10x10)

array_10x10[0,:] = 1
array_10x10[-1,:] = 1
array_10x10[:, 0] = 1
array_10x10[:, -1] =1

print("\n Matriz com perimetro 1:")
print(array_10x10)

Matriz original: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 Matriz com perimetro 1:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
